baseURL = "https://boltzmann-brain.github.io/"
title = "Leif Hancox-Li"

theme = "hugo-coder"

languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Leif Hancox-Li"
    description = "Leif Hancox-Li's personal website"
    info = "Data Scientist and Researcher in Responsible AI"
    avatarurl = "images/smiling-alien.png"
    footercontent = "No, the code does not document itself."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/boltzmann-brain"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/leif-hancox-li-1a6a7a132/"


[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Experience"
    weight = 2
    url  = "/resume/"
[[menu.main]]
    name = "Papers"
    weight = 3
    url = "/papers/"
[[menu.main]]
    name = "Blog"
    weight = 4
    url = "/posts/"